defectdojo:
  url: ""  # Замените на ваш URL
  api_key: ""             # Замените на ваш API ключ

settings:
  severity_levels: ["CRITICAL", "HIGH", "MEDIUM", "LOW"]
  require_exploits: true

risk_accept:
  Level: ["Medium", "Low"]
  WithExploits: false
  EPSS: 100
  CisaKev: false
  AllRequired: true